# Generated by Django 5.0.3 on 2024-03-13 01:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashStations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('title', models.CharField(max_length=255, verbose_name='Nome da Estação')),
            ],
            options={
                'verbose_name': 'Estação de Lixo',
                'verbose_name_plural': 'Estações de Lixo',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('status', models.IntegerField(choices=[('created', 'Criado'), ('closed', 'Fechado')], default='created', verbose_name='Situação')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkers', to=settings.AUTH_USER_MODEL, verbose_name='Conferente')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='store.trashstations', verbose_name='Estação de Lixo')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discarts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Indentificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado às')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado às')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Deletado às')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('quantity', models.IntegerField(verbose_name='Quantidade Descartada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discarts', to='store.trashstations', verbose_name='Estação de Lixo')),
            ],
            options={
                'verbose_name': 'Descarte',
                'verbose_name_plural': 'Descartes',
                'ordering': ['-created_at'],
            },
        ),
    ]
