# Generated by Django 5.0.3 on 2024-03-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashstations',
            name='quantity_max',
            field=models.IntegerField(default=100, verbose_name='Quantidade Máxima'),
        ),
    ]
