# Generated by Django 5.0.3 on 2024-03-14 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_trashstations_quantity_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='store.trashstations', verbose_name='Estação de Lixo'),
        ),
    ]
